server:
  port: 8090

spring:
  main:
    web-application-type: servlet
  application:
    name: users-service
    pattern-matching: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}



  # ----- Spring Kafka base (used by AdminClient, health, etc.) -----
  kafka:
      bootstrap-servers: ${KAFKA_BROKERS:kafka:9092}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          acks: all
          enable.idempotence: true
          max.in.flight.requests.per.connection: 5
          retries: 10
      user-topic: user.created

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_REALM:chat-local}
    admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.stream: INFO
    org.springframework.kafka: INFO
    org.springframework.security: WARN
