server:
  port: 8080

spring:
  application:
    name: users-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
